export {default as About} from './about/about'
export {default as Footer} from './footer/footer'
export {default as Hero} from './hero/hero'
export {default as MiniProject} from './miniProject/miniProject'
export {default as NavBar} from './navBar/navBar'
export {default as Portfolio} from './portfolio/porfolio'